Screamy\PriceImporter\Entity\Brand:
  type: entity
  table: price_import_brand
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
      nullable: false