Screamy\PriceImporter\Entity\Category:
  type: entity
  table: price_import_category
  repositoryClass: Screamy\PriceImporter\Repository\CategoryRepository
  id:
    id:
      type: integer
  fields:
    title:
      type: string
      length: 255
      nullable: true
  manyToOne:
    parent:
      type: int
      nullable: true
      options:
        unsigned: true
      targetEntity: \Screamy\PriceImporter\Entity\Category
      joinColumn:
        name: parent_id
        referencedColumnName: id
      inversedBy: children
  oneToMany:
    children:
      type: int
      nullable: true
      options:
        unsigned: true
      targetEntity: \Screamy\PriceImporter\Entity\Category
      joinColumn:
        name: id
        referencedColumnName: parent_id
      mappedBy: parent