Screamy\PriceImporter\Entity\Product:
  type: entity
  table: price_import_product
  repositoryClass: Screamy\PriceImporter\Repository\ProductRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    sku:
      type: string
      length: 255
      unique: true
    title:
      type: string
      length: 255
      nullable: false
    price:
      type: float
      nullable: false
      options:
        unsigned: true
    imagePath:
      type: string
      nullable: true
      length: 1024
    quantity:
      type: integer
      nullable: false
      options:
        default: 0
        unsigned: true
    imported:
      type: boolean
      nullable: false
  manyToOne:
    category:
      type: integer
      options:
        unsigned: true
      targetEntity: \Screamy\PriceImporter\Entity\Category
      joinColumn:
        name: category_id
        referencedColumnName: id
    brand:
      type: integer
      options:
        unsigned: true
      targetEntity: \Screamy\PriceImporter\Entity\Brand
      joinColumn:
        name: brand_id
        referencedColumnName: id

  manyToMany:
    properties:
      name: property_value_id
      type: integer
      options:
        unsigned: true
      targetEntity: Screamy\PriceImporter\Entity\PropertyValue

      joinTable:
        name: price_import_product_properties
        joinColumns:
          product_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          property_value_id:
            referencedColumnName: id


